# Generated by Django 3.2.9 on 2021-11-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25, null=True, unique=True)),
                ('password', models.CharField(max_length=25, null=True)),
                ('previous_password', models.CharField(max_length=25, null=True)),
                ('last_login_time', models.DateField(null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'En_Credentials',
            },
        ),
    ]
