# Generated by Django 3.2.9 on 2021-11-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('display_picture', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('subscribe_for_updates', models.BooleanField(default=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.credentials')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
            options={
                'verbose_name': 'en_users',
                'db_table': 'en_users',
            },
        ),
        migrations.DeleteModel(
            name='EnUsers',
        ),
    ]
